; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = arduino
build_flags =
    -DENABLE_DEBUG
lib_deps =
    tinyusb
    arduino-libraries/Keyboard
    arduino-libraries/Mouse
    arduino-libraries/SD
    https://github.com/esphome/ESPAsyncWebServer.git

[env:esp32-s2-kaluga-4MB]
board = esp32-s2-kaluga-1
monitor_speed = 115200

board_build.flash_mode = dio
board_upload.flash_size = 4MB
board_build.partitions = partitions/4MB_HID_MSC.csv

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DUSB_VID=0xCafe
  -DUSB_PID=0x4001

upload_speed = 460800